[settings]
always_keep_download = true
always_keep_install = true
env_file = "env"
asdf_compat = true
experimental = true
not_found_auto_install = false
trusted_config_paths = [
    "~/Projects/github.com/btkostner",
    "~/Projects/github.com/hiivemarkets",
]

[tools]
act = "latest"
buf = "latest"
deno = "latest"
elixir = "latest"
erlang = "latest"
fnox = "latest"
go = "latest"
node = "latest"
python = "latest"
rust = "latest"
zig = "latest"
